import { defineConfig } from "vitepress";

/** Local preview of docs/ (monorepo). Published site uses vireondynamics-website/docs-portal. */
export default defineConfig({
  title: "Liminal",
  description: "Local-first agent harness documentation",
  srcDir: "..",
  outDir: ".vitepress/dist",
  cleanUrls: true,
  ignoreDeadLinks: [
    /^\.\.\//,
    /^\.\.\/\.\.\//,
    /^\.\.\/\.\.\/\.\.\//,
    /^\.\/\.\.\/\.\.\//,
    /\/packages\/(enterprise|control-plane)\//,
    /\/\.env\.example$/,
  ],
  themeConfig: {
    nav: [
      { text: "Install", link: "/start/install" },
      { text: "Connectors", link: "/guides/connectors" },
      { text: "Quickstart", link: "/start/quickstart" },
      { text: "Troubleshooting", link: "/operations/troubleshooting" },
    ],
    sidebar: [
      {
        text: "Start here",
        items: [
          { text: "Overview", link: "/" },
          { text: "Install", link: "/start/install" },
          { text: "Quickstart", link: "/start/quickstart" },
          { text: "Configuration basics", link: "/start/configuration-basics" },
        ],
      },
      {
        text: "Concepts",
        items: [
          { text: "Architecture", link: "/concepts/architecture" },
          { text: "Harness protocol", link: "/concepts/harness-protocol" },
          { text: "Runtime behavior", link: "/concepts/runtime-behavior" },
          { text: "Identity stack", link: "/concepts/identity-stack" },
          { text: "Memory and vault", link: "/concepts/memory-and-vault" },
          { text: "Persona system", link: "/concepts/persona-system" },
          { text: "UI streaming", link: "/concepts/ui-streaming" },
          { text: "Rich message rendering", link: "/concepts/rich-message-rendering" },
          { text: "Liminal desktop apps", link: "/concepts/liminal-apps" },
        ],
      },
      {
        text: "Integrations",
        items: [
          { text: "Connectors hub", link: "/guides/connectors" },
          { text: "Multi-account mail", link: "/guides/multi-account-mail" },
          { text: "Inbox watcher", link: "/guides/inbox-watcher" },
          { text: "Compose dock & attachments", link: "/guides/compose-dock-and-attachments" },
          { text: "Google Workspace", link: "/guides/google-workspace" },
          { text: "Microsoft 365", link: "/guides/microsoft-365" },
          { text: "Azure", link: "/guides/azure" },
          { text: "GitHub", link: "/guides/github" },
          { text: "Slack", link: "/guides/slack" },
          { text: "Linear", link: "/guides/linear" },
          { text: "Notion", link: "/guides/notion" },
          { text: "Xero", link: "/guides/xero" },
          { text: "YouTube", link: "/guides/youtube" },
        ],
      },
      {
        text: "Guides",
        items: [
          { text: "Memory & recall", link: "/guides/memory-and-recall" },
          { text: "Web research", link: "/guides/web-research" },
          { text: "Browser automation", link: "/guides/browser-automation" },
          { text: "Document engine", link: "/guides/document-engine" },
          { text: "Voice (TTS & dictation)", link: "/guides/voice" },
          { text: "Sub-agents & orchestration", link: "/guides/sub-agents-and-orchestration" },
          { text: "Dynamic workflows", link: "/guides/dynamic-workflows" },
          { text: "Reasoning & effort", link: "/guides/reasoning-and-effort" },
          { text: "Tuning via Settings", link: "/guides/tuning-via-settings" },
          { text: "Running the eval suite", link: "/guides/running-eval" },
          { text: "Sandbox capability lab", link: "/guides/sandbox-capability-lab" },
          { text: "Persona bootstrap", link: "/guides/persona-bootstrap" },
          { text: "Vault briefs & updates", link: "/guides/vault-briefs-and-updates" },
          { text: "Agentcard", link: "/guides/agentcard" },
          { text: "Remote sessions", link: "/guides/remote-sessions" },
        ],
      },
      {
        text: "Pro & Enterprise",
        items: [
          { text: "Pro & Enterprise features", link: "/reference/pro-and-enterprise" },
          { text: "Accounts & licensing", link: "/guides/accounts-and-licensing" },
          { text: "Managed inference", link: "/guides/managed-inference" },
          { text: "Enterprise features", link: "/guides/enterprise-features" },
          { text: "Team memory", link: "/guides/team-memory" },
          { text: "Enterprise Edition", link: "/reference/enterprise-edition" },
          { text: "License", link: "/reference/license" },
        ],
      },
      {
        text: "Reference",
        items: [
          { text: "Changelog", link: "/reference/changelog" },
          { text: "Roadmap", link: "/reference/roadmap" },
          { text: "Environment (generated)", link: "/reference/environment" },
          { text: "Web API", link: "/reference/web-api" },
          { text: "Events", link: "/reference/events" },
          { text: "Tool families", link: "/reference/tools/" },
          { text: "Inference path validation", link: "/reference/inference-path-validation" },
          { text: "Configuration (narrative)", link: "/configuration" },
        ],
      },
      {
        text: "Operations",
        items: [
          { text: "Troubleshooting", link: "/operations/troubleshooting" },
          { text: "Profiles", link: "/operations/profiles" },
        ],
      },
    ],
    search: { provider: "local" },
  },
});
