/** @typedef {{ id: string; label: string; baseURL: string; model: string; apiKey: string; needsKey: boolean; hint?: string }} ProviderPreset */

/** @type {ProviderPreset[]} */
export const PROVIDER_PRESETS = [
  {
    id: "deepseek-v4",
    label: "OpenRouter — DeepSeek V4 Pro + Flash (recommended)",
    baseURL: "https://openrouter.ai/api/v1",
    model: "deepseek/deepseek-v4-pro",
    apiKey: "",
    needsKey: true,
    hint: "Latest DeepSeek. Main: v4-pro. Fast: v4-flash. DeepInfra pin.",
  },
  {
    id: "nemotron-3-ultra",
    label: "Nemotron 3 Ultra (free)",
    baseURL: "https://openrouter.ai/api/v1",
    model: "nvidia/nemotron-3-ultra-550b-a55b:free",
    apiKey: "",
    needsKey: true,
    hint: "NVIDIA free MoE agent model (1M ctx). No confidential/personal data on NVIDIA free tier.",
  },
  {
    id: "free-router-nemotron-ultra",
    label: "Free mix — OpenRouter router + Nemotron 3 Ultra",
    baseURL: "https://openrouter.ai/api/v1",
    model: "openrouter/free",
    apiKey: "",
    needsKey: true,
    hint: "Main: openrouter/free. Fast: nvidia/nemotron-3-ultra-550b-a55b:free.",
  },
  {
    id: "nex-n2-pro-free",
    label: "Nex AGI — Nex N2 Pro (free, native vision)",
    baseURL: "https://openrouter.ai/api/v1",
    model: "nex-agi/nex-n2-pro:free",
    apiKey: "",
    needsKey: true,
    hint: "Free MoE agent model with text+image input on the main API (262K ctx).",
  },
  {
    id: "openrouter-owl-stealth",
    label: "OpenRouter Stealth — Owl Alpha (Hermes)",
    baseURL: "https://openrouter.ai/api/v1",
    model: "openrouter/owl-alpha",
    apiKey: "",
    needsKey: true,
    hint: "Stealth owl-alpha — must use Stealth provider (not DeepInfra).",
  },
  {
    id: "mimo-v2.5",
    label: "OpenRouter — Xiaomi MiMo V2.5 Pro + MiMo V2.5",
    baseURL: "https://openrouter.ai/api/v1",
    model: "xiaomi/mimo-v2.5-pro",
    apiKey: "",
    needsKey: true,
    hint: "Latest MiMo line.",
  },
  {
    id: "google-gemini-3.5",
    label: "OpenRouter — Gemini 3.5 Flash + 3.1 Flash Lite",
    baseURL: "https://openrouter.ai/api/v1",
    model: "google/gemini-3.5-flash",
    apiKey: "",
    needsKey: true,
    hint: "Latest Google pair (replaces Gemini 2.5).",
  },
  {
    id: "anthropic-claude-opus-4.7",
    label: "OpenRouter — Claude Opus 4.7 + Opus Fast",
    baseURL: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-opus-4.7",
    apiKey: "",
    needsKey: true,
    hint: "Frontier Anthropic 4.7 line.",
  },
  {
    id: "anthropic-claude-sonnet-4.6",
    label: "OpenRouter — Claude Sonnet 4.6 + Haiku 4.5",
    baseURL: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-sonnet-4.6",
    apiKey: "",
    needsKey: true,
    hint: "Balanced Anthropic — latest Sonnet on OpenRouter.",
  },
  {
    id: "openai-gpt-5.5",
    label: "OpenRouter — GPT-5.5 + GPT-5.4 mini",
    baseURL: "https://openrouter.ai/api/v1",
    model: "openai/gpt-5.5",
    apiKey: "",
    needsKey: true,
    hint: "Latest OpenAI pair. Fast: gpt-5.4-mini.",
  },
  {
    id: "qwen-3.6",
    label: "OpenRouter — Qwen 3.6 Plus + Flash",
    baseURL: "https://openrouter.ai/api/v1",
    model: "qwen/qwen3.6-plus",
    apiKey: "",
    needsKey: true,
    hint: "Latest Qwen agent pair.",
  },
  {
    id: "mix-claude-sonnet-4.6-deepseek-flash",
    label: "OpenRouter — Sonnet 4.6 + DeepSeek Flash (mix)",
    baseURL: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-sonnet-4.6",
    apiKey: "",
    needsKey: true,
    hint: "Best quality/$ for long harness runs.",
  },
  {
    id: "mix-gemini-3.5-deepseek-flash",
    label: "OpenRouter — Gemini 3.5 Flash + DeepSeek Flash (mix)",
    baseURL: "https://openrouter.ai/api/v1",
    model: "google/gemini-3.5-flash",
    apiKey: "",
    needsKey: true,
    hint: "Research/multimodal main + cheap sidecars.",
  },
  {
    id: "deepseek",
    label: "DeepSeek API direct + deepseek-chat",
    baseURL: "https://api.deepseek.com/v1",
    model: "deepseek-chat",
    apiKey: "",
    needsKey: true,
    hint: "Get a key at https://platform.deepseek.com/",
  },
  {
    id: "lmstudio",
    label: "Local LM Studio (http://localhost:1234/v1)",
    baseURL: "http://localhost:1234/v1",
    model: "qwen/qwen3.5-9b",
    apiKey: "lm-studio",
    needsKey: false,
    hint: "Load a model in LM Studio and enable the local server.",
  },
  {
    id: "ollama",
    label: "Local Ollama (http://localhost:11434/v1)",
    baseURL: "http://localhost:11434/v1",
    model: "qwen3.5:9b",
    apiKey: "ollama",
    needsKey: false,
    hint: "Run `ollama pull qwen3.5:9b` (or your model tag).",
  },
  {
    id: "custom",
    label: "Custom OpenAI-compatible endpoint",
    baseURL: "",
    model: "",
    apiKey: "",
    needsKey: true,
  },
];

/** @param {number} index */
export function presetByIndex(index) {
  return PROVIDER_PRESETS[index - 1] ?? null;
}

/** @param {string} id */
export function presetById(id) {
  return PROVIDER_PRESETS.find((p) => p.id === id) ?? null;
}
