import type { AgentHarness } from "@liminal/core";
import { defineTool } from "./helpers.js";
import { buildRichPersonaBlock, type PersonaProfile } from "./persona_presets.js";
import { generatePersonaProfile } from "./persona_generator.js";
import { atomicUpdate } from "./notes_store.js";

// ─── Input parser ─────────────────────────────────────────────────────────────

interface ParsedInput {
  coreInput: string;
  strength: number;
  modifier?: string;
}

/**
 * Parse a set_persona input string for strength and modifier directives.
 *
 * Supported formats:
 *   "dry British valet"              → coreInput="dry British valet", strength=8
 *   "dry British valet 9"           → strength=9
 *   "dry British valet strength:7"  → strength=7
 *   "pirate narrator but calmer"    → modifier="calmer"
 *   "pirate 9 but more technical"   → strength=9, modifier="more technical"
 */
function parsePersonaInput(input: string): ParsedInput {
  let text = input.trim();
  let strength = 8;
  let modifier: string | undefined;

  const butMatch = text.match(/\s+but\s+(.+)$/i);
  if (butMatch) {
    modifier = butMatch[1].trim();
    text = text.slice(0, text.length - butMatch[0].length).trim();
  }

  const strengthExplicit = text.match(/\bstrength[:\s]+(\d{1,2})\b/i);
  if (strengthExplicit) {
    const n = parseInt(strengthExplicit[1], 10);
    if (n >= 1 && n <= 10) strength = n;
    text = text.replace(strengthExplicit[0], "").trim();
  } else {
    const trailingDigit = text.match(/\s+([1-9]|10)$/);
    if (trailingDigit) {
      strength = parseInt(trailingDigit[1], 10);
      text = text.slice(0, text.length - trailingDigit[0].length).trim();
    }
  }

  return { coreInput: text, strength, modifier };
}

function isResetToDefaultRequest(coreInput: string): boolean {
  const k = coreInput.toLowerCase().trim();
  return k === "default" || k === "liminal" || k === "reset" || k === "clear";
}

// ─── Memory persistence ───────────────────────────────────────────────────────

const PERSONA_MEMORY_KEY = "persona:active_profile";
const PERSONA_NAME_KEY = "persona:active_name";

async function persistPersona(profile: PersonaProfile): Promise<void> {
  await atomicUpdate((notes) => ({
    ...notes,
    [PERSONA_MEMORY_KEY]: JSON.stringify(profile),
    [PERSONA_NAME_KEY]: profile.name,
  }));
}

async function clearPersistedPersona(): Promise<void> {
  await atomicUpdate((notes) => {
    const next = { ...notes };
    delete next[PERSONA_MEMORY_KEY];
    delete next[PERSONA_NAME_KEY];
    return next;
  });
}

// ─── Tool factory ─────────────────────────────────────────────────────────────

/**
 * Factory: creates the set_persona tool bound to a specific harness instance.
 *
 * Usage:
 *   set_persona("default") | "reset" | "liminal" | "clear"  → restore default inception voice (no LLM)
 *   set_persona("sarcastic Victorian scientist 9")        → model-generated persona
 *   set_persona("formal British assistant but sharper wit") → modifier + generation
 *
 * All custom voices are generated by the model from natural language (requires OPENROUTER_API_KEY).
 */
export function createSetPersonaTool(harness: AgentHarness) {
  return defineTool({
    name: "set_persona",
    description:
      "WHAT: Change your communication style and personality inline during the conversation.\n" +
      "WHEN: The user asks you to change personality, tone, or speaking style.\n" +
      "NOT WHEN: The user asks you to roleplay a scenario — persona changes STYLE, not task behavior.\n\n" +
      "ARGS:\n" +
      "  input — natural-language voice (required), OR one of: default, reset, liminal, clear (restores default; no LLM).\n\n" +
      "STRENGTH: append 1-10 — e.g. 'noir detective narrator 9' or 'strength:6'\n" +
      "MODIFIER: append 'but ...' — e.g. 'chipper coworker but less chatty'\n\n" +
      "EFFECT: Tone and vocabulary change on the next turn. Operational rules unchanged.\n" +
      "Custom personas are generated via the model and saved to session memory.",
    requiresApproval: false,
    parameters: {
      type: "object",
      properties: {
        input: {
          type: "string",
          description:
            "Voice description in plain language, OR default/reset/liminal/clear to restore the default agent. " +
            "Optional: number 1-10 for strength, 'but ...' for modifiers.",
          minLength: 1,
        },
      },
      required: ["input"],
      additionalProperties: false,
    },
    handler: async (args) => {
      const { coreInput, strength, modifier } = parsePersonaInput(args["input"] as string);

      if (isResetToDefaultRequest(coreInput)) {
        harness.resetPersona();
        try {
          await clearPersistedPersona();
        } catch {
          // non-fatal
        }
        return {
          ok: true,
          output:
            "Persona cleared — restored default inception identity (no model call).\n" +
            "Operational rules unchanged.",
        };
      }

      if (!coreInput) {
        return {
          ok: false,
          error: "Describe a voice (e.g. 'dry British assistant with understated wit') or use default/reset to clear.",
        };
      }

      const { openRouterApiKey, model, baseURL } = harness.config;
      if (!openRouterApiKey) {
        return {
          ok: false,
          error:
            "Cannot generate persona: OPENROUTER_API_KEY not configured. " +
            "You can still run set_persona(\"default\") or set_persona(\"reset\") to restore the default voice.",
        };
      }

      const profile = await generatePersonaProfile(
        coreInput,
        strength,
        modifier,
        openRouterApiKey,
        model,
        baseURL
      );

      const block = buildRichPersonaBlock(profile);

      harness.setPersona({ name: profile.name, description: profile.coreIdentity }, block);

      try {
        await persistPersona(profile);
      } catch {
        // Non-fatal — persona is applied even if memory write fails
      }

      const modifierNote = profile.modifier ? ` (modifier: "${profile.modifier}")` : "";
      const strengthNote =
        profile.strength >= 9
          ? "maximum commitment"
          : profile.strength >= 7
            ? "strong"
            : profile.strength >= 5
              ? "moderate"
              : "subtle";

      return {
        ok: true,
        output:
          `Persona applied: ${profile.name} [generated, strength ${profile.strength}/10 — ${strengthNote}]${modifierNote}.\n` +
          `${profile.coreIdentity}\n` +
          `Operational rules unchanged. Tone and vocabulary updated immediately.`,
      };
    },
  });
}
