import type { AgentHarness } from "@liminal/core";
import { defineTool } from "../../shared/helpers.js";
import type { RuntimePersonaProfile } from "@liminal/core";
import {
  applyPersonaProfileToHarness,
  installDefaultPersonaArtifacts,
  generatePersonaFromInput,
  isResetToDefaultRequest,
  parsePersonaInput,
} from "./persona_runtime.js";

// ─── Tool factory ─────────────────────────────────────────────────────────────

/**
 * Factory: creates the set_persona tool bound to a specific harness instance.
 *
 * Usage:
 *   set_persona("default") | "reset" | "liminal" | "clear"  → restore default inception voice (no LLM)
 *   set_persona("sarcastic Victorian scientist 9")        → model-generated persona
 *   set_persona("formal British assistant but sharper wit") → modifier + generation
 *
 * All custom voices are generated by the model from natural language (requires OPENROUTER_API_KEY).
 */
export function createSetPersonaTool(harness: AgentHarness) {
  return defineTool({
    name: "set_persona",
    description:
      "WHAT: Change the **default written voice and stance** (tone, diction, judgment habits) for this harness session.\n" +
      "WHEN: The user asks you to change personality, tone, or speaking style.\n" +
      "NOT WHEN: The user asks you to **roleplay a scenario** (fiction/improv) — persona is **how you write as the agent**, not a separate actor or plot.\n\n" +
      "ARGS:\n" +
      "  input — natural-language voice (required), OR one of: default, reset, liminal, clear (restores default; no LLM).\n\n" +
      "STRENGTH: append 1-10 — e.g. 'noir detective narrator 9' or 'strength:6'\n" +
      "MODIFIER: append 'but ...' — e.g. 'chipper coworker but less chatty'\n\n" +
      "EFFECT: Tone and vocabulary change on the next turn. Operational rules unchanged.\n" +
      "Custom personas are generated via the model and saved to session memory.",
    requiresApproval: false,
    parameters: {
      type: "object",
      properties: {
        input: {
          type: "string",
          description:
            "Voice description in plain language, OR default/reset/liminal/clear to restore the default agent. " +
            "Optional: number 1-10 for strength, 'but ...' for modifiers.",
          minLength: 1,
        },
      },
      required: ["input"],
      additionalProperties: false,
    },
    handler: async (args) => {
      const { coreInput, strength, modifier } = parsePersonaInput(args["input"] as string);

      if (isResetToDefaultRequest(coreInput)) {
        await installDefaultPersonaArtifacts(harness);
        return {
          ok: true,
          output:
            "Default Liminal persona installed (profile, soul, HUD theme, UI copy).\n" +
            "Operational rules unchanged.",
        };
      }

      if (!coreInput) {
        return {
          ok: false,
          error: "Describe a voice (e.g. 'dry British assistant with understated wit') or use default/reset to clear.",
        };
      }

      if (!harness.config.openRouterApiKey) {
        return {
          ok: false,
          error:
            "Cannot generate persona: OPENROUTER_API_KEY not configured. " +
            "You can still run set_persona(\"default\") or set_persona(\"reset\") to restore the default voice.",
        };
      }

      const bundle = await generatePersonaFromInput(harness, coreInput, strength, modifier);
      const profile = bundle.profile;
      await applyPersonaProfileToHarness(harness, profile);

      try {
        await harness.patchRuntimePreferences(
          {
            persona: {
              bootstrapCompleted: true,
              sourcePrompt: coreInput,
              activeProfile: profile as RuntimePersonaProfile,
              controls: bundle.defaultControls,
              updatedAt: Date.now(),
            },
          },
          { persist: true }
        );
      } catch {
        // Non-fatal — persona is applied even if memory write fails
      }

      const modifierNote = profile.modifier ? ` (modifier: "${profile.modifier}")` : "";
      const strengthNote =
        profile.strength >= 9
          ? "maximum commitment"
          : profile.strength >= 7
            ? "strong"
            : profile.strength >= 5
              ? "moderate"
              : "subtle";

      return {
        ok: true,
        output:
          `Persona applied: ${profile.name} [generated, strength ${profile.strength}/10 — ${strengthNote}]${modifierNote}.\n` +
          `${profile.coreIdentity}\n` +
          `Operational rules unchanged. Tone and vocabulary updated immediately.`,
      };
    },
  });
}
